steps:
- name: 'gcr.io/cloud-builders/docker'
  id: 'Build'
  args: ["build", "-t", "gcr.io/$PROJECT_ID/$REPO_NAME:$REVISION_ID", "."]
- name: 'gcr.io/cloud-builders/gcloud'
  id: 'Update manifest'
  entrypoint: /bin/sh
  args:
  - '-c'
  - |
     sed "s/GOOGLE_CLOUD_PROJECT/${PROJECT_ID}/g" k8s/deployment.yaml 
- name: 'gcr.io/cloud-builders/docker'
  id: 'Push'
  args: ["push", "gcr.io/$PROJECT_ID/$REPO_NAME:$REVISION_ID"]
- name: 'gcr.io/cloud-builders/gke-deploy:stable'
  id: 'Deploy'
  args:
  - 'run'
  - '--filename=k8s'
  - '--image=gcr.io/$PROJECT_ID/$REPO_NAME:$REVISION_ID'
  - '--location=us-central1-c'
  - '--cluster=gke-deploy-cluster'
