steps:
- name: 'gcr.io/cloud-builders/docker'
  id: 'Build'
  args: ["build","-t","$REPO_NAME:$REVISION_ID",".","-f","$_DOCKERFILE_PATH"]
- name: 'gcr.io/cloud-builders/docker'
  args: ["push", "gcr.io/$PROJECT_ID/$REPO_NAME:$REVISION_ID"]
- name: 'gcr.io/cloud-builders/gke-deploy:stable'
  args:
  - 'run'
  - '--image=gcr.io/$PROJECT_ID/$REPO_NAME:$REVISION_ID'
  - '--location=europe-north1'
  - '--cluster=gke-deploy-cluster'
