steps:
- name: 'gcr.io/cloud-builders/docker'
  id: 'Build'
  args: ["build","-t","$_IMAGE_NAME:$_IMAGE_VERSION",".","-f","$_DOCKERFILE_PATH"]
- name: 'gcr.io/cloud-builders/docker'
  args: ["push", "gcr.io/$PROJECT_ID/$_IMAGE_NAME:$_IMAGE_VERSION"]
- name: 'gcr.io/cloud-builders/gke-deploy:stable'
  args:
  - 'run'
  - '--image=gcr.io/$PROJECT_ID/$_IMAGE_NAME:$_IMAGE_VERSION'
  - '--location=us-central1'
  - '--cluster=gke-deploy-cluster'
