apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: gke-demo-1
  name: gke-demo-1
spec:
  replicas: 2
  selector:
    matchLabels:
      run: gke-demo-1
  template:
    metadata:
      labels:
        run: gke-demo-1
    spec:
      containers:
      - image: gcr.io/rdvk-gke-test-1/gke-demo-1:latest
        name: gke-demo-1
        ports:
        - containerPort: 8080
